spring:
  application:
    name: simple-exchange
  r2dbc:
    url: r2dbc:h2:file:///././exchangedb
    username: sa
    password: sa
  flyway:
    url: jdbc:h2:file:././exchangedb
    user: sa
    password: sa
